name: "React to S3 Action"
description: "Build a React.js web app and sync to an AWS S3 repository"
author: chknim
runs:
  using: docker
  image: Dockerfile
branding:
  icon: upload-cloud
  color: green
